apiVersion: v1
kind: Service
metadata:
  name: jycloud-gateway
spec:
  type: NodePort
  ports:
  - port: 8060
    nodePort: 8060
  selector:
    app: jycloud-gateway
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jycloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jycloud-gateway
  template:
    metadata:
      labels:
        app: jycloud-gateway
    spec:
      hostAliases:
      - ip: "192.168.128.160"
        hostnames:
        - "config.jycloud.com"
        - "eureka.jycloud.com"
        - "web.jycloud.com"
        - "manage.jycloud.com"
      containers:
      - name: jycloud-gateway
        image: 192.168.1.108:5000/org.jygroup.cloud/gateway:V1.0.6
        ports:
        - containerPort: 8060
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'prod'
