apiVersion: v1
kind: Service
metadata:
  name: jycloud-message
spec:
  type: NodePort
  ports:
  - port: 8011
    nodePort: 8011
  selector:
    app: jycloud-message
apiVersion: v1
kind: Service
metadata:
  name: jycloud-message02
spec:
  type: NodePort
  ports:
  - port: 1157
    nodePort: 1157
  selector:
    app: jycloud-message
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jycloud-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jycloud-message
  template:
    metadata:
      labels:
        app: jycloud-message
    spec:
      hostAliases:
      - ip: "192.168.128.160"
        hostnames:
        - "config.jycloud.com"
        - "eureka.jycloud.com"
        - "web.jycloud.com"
        - "manage.jycloud.com"
      containers:
      - name: jycloud-message
        image: 192.168.1.108:5000/com.ciip.cloud.core/message:V1.1.5
        ports:
        - containerPort: 8011
        - containerPort: 1157
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'prod'
        volumeMounts:
        - mountPath: /service/resources/jyj
          name: jycloud-message
      volumes:
      - name: jycloud-message
        hostPath:
          path: /service/resources/jyj
          type: Directory
