apiVersion: v1
kind: Service
metadata:
  name: jycloud-web
spec:
  type: NodePort
  ports:
  - port: 8771
    nodePort: 8771
  selector:
    app: jycloud-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jycloud-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jycloud-web
  template:
    metadata:
      labels:
        app: jycloud-web
    spec:
      hostAliases:
      - ip: "192.168.128.160"
        hostnames:
        - "config.jycloud.com"
        - "eureka.jycloud.com"
        - "web.jycloud.com"
        - "manage.jycloud.com"
      containers:
      - name: jycloud-web
        image: 192.168.1.108:5000/com.ciip.cloud.core.jyj/web:V1.1.3
        ports:
        - containerPort: 8771
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: 'prod'
        volumeMounts:
        - mountPath: /service/resources/jyj/upload
          name: service
      volumes:
      - name: service
        hostPath:
          path: /service/resources/jyj/upload
          type: Directory
